DELETE http://127.0.0.1:8080/events/4/register
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1pa2VAZ21haWwuY29tIiwiZXhwIjoxNzI4MDI1NDQ0LCJpZCI6Mn0.QqgiW_3NQ1KeK8FGFDa9rdaYhAI07QT4ZOJ5vsIzJFM