POST http://127.0.0.1:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRlZXBha3JlZGR5MUBnbWFpbC5jb20iLCJleHAiOjE3Mjc5NjI2MDAsImlkIjoxfQ.9OwtOKB0599zjeAHfxZDJaacYFdfmOnRC-HCMmqNZBc

{
    "name": "ColdPlay",
    "description": "Coldplay are a British rock band formed in London in 1997",
    "location": "Mumbai, India",
    "eventDate": "2025-01-12T18:30:00.000Z"
}