POST http://127.0.0.1:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1pa2UxQGdtYWlsLmNvbSIsImV4cCI6MTcyODE0NDg0MiwiaWQiOjF9.LvVSK2oxxTgqjfUkaABIm_F2kJaO5FSpMCmyORBiAug

{
    "name": "ColdPlay",
    "description": "Coldplay are a British rock band formed in London in 1997",
    "location": "Mumbai, India",
    "eventDate": "2025-01-12T18:30:00.000Z"
}